### ISSUE TITLE
Error in cloud plot generation from terminal

### ISSUE THREAD

**Issue by Stevogallo** [RAMP-project/RAMP#107]
when running from input_file_x.py from terminal, it runs, generates the series plot and stops before generating cloud plot showing error:

% python <path>\input_file_5.py

[...]

Traceback (most recent call last):
  File "C:\Users\stevo\OneDrive\Desktop\RAMP-main\ramp\example\input_file_5.py", line 281, in <module>
    pp.Profile_cloud_plot(Profiles_list, Profiles_avg)
  File "C:\Users\stevo\.conda\envs\ramp\lib\site-packages\ramp\post_process\post_process.py", line 38, in Profile_cloud_plot
    plt.plot(np.arange(1440), n, "#b0c4de")
  File "C:\Users\stevo\.conda\envs\ramp\lib\site-packages\matplotlib\pyplot.py", line 2812, in plot
    return gca().plot(
  File "C:\Users\stevo\.conda\envs\ramp\lib\site-packages\matplotlib\axes\_axes.py", line 1688, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\Users\stevo\.conda\envs\ramp\lib\site-packages\matplotlib\axes\_base.py", line 311, in __call__
    yield from self._plot_args(
  File "C:\Users\stevo\.conda\envs\ramp\lib\site-packages\matplotlib\axes\_base.py", line 504, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1440,) and (1,)

**Comment by Bachibouzouk** [comment]
Hello @Stevogallo, could you share your input_file?

**Comment by Stevogallo** [comment]
It's input_file_1 already present in the "example" folder, renamed to input_file_5 to test also the old bug
